#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80


#sudo apt-get update -y -qq && \
#	 sudo apt-get install nginx -y

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
#sudo chown -R "$USER":"$USER" /var/www/html
#sudo chmod -R 755 /var/www

# Backup default index
#cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
#echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
service start nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo rm /var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart
