#!/usr/bin/env bash
# installing nginx to listen on 80
# and return "Hello world" as output


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
# sudo ufw allow 'Nginx HTTP'
service start nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
