#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
service start nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo rm /var/www/html/index.nginx-debian.html
