#!/usr/bin/env bash
# installing nginx to listen on 80
# and return "Hello world" as output


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
# sudo ufw allow 'Nginx HTTP'
service start nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
service nginx restart
