#!/usr/bin/env bash
# Fizzbyzz but in shrll script

n=1

while [ $n -le 100 ]
do
	if [ $((n % 3)) -eq 0 -a $((n % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((n % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((n % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$n"
	fi
	n=$((n+1))
done
