#!/usr/bin/env bash
# Using while loop, if, elif and else

c=1

while [ $c -le 10 ]
do
	if [ $c == 4 ]
	then
		echo "bad luck"
	elif [ $c == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	c=$(( c + 1))
done
