#!/usr/bin/env bash
# Usung case ststenent iwhile loop

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	count=$(( count + 1 ))
done
